# yaml 配置
version: "3.7"
services:
  redis507:
    image: "redis:5.0.7"
    ports:
      - "26379:6379"
  mysql8:
    image: "mysql:8"
    ports:
      - "23306:3306"
    command: "--init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "bluebell_pre"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./init.sql:/data/application/init.sql
  bluebell_app:
    build: .
    command: sh -c "./wait-for.sh redis507:6379 mysql8:3306 -- ./bluebell ./conf/config.yaml"
    depends_on:
      - mysql8
      - redis507
    ports:
      - "8081:8081"